marcador/urls.py
from django.urls import path
from marcador import views


app_name = 'marcador'
urlpatterns = [
    path('user/<slug:username>/', views.bookmark_user,
         name='marcador_bookmark_user'),
    path('create/', views.bookmark_create,
         name='marcador_bookmark_create'),
    path('edit/<int:pk>', views.bookmark_edit,
          name='marcador_bookmark_edit'),
    path('', views.bookmark_list, name='marcador_bookmark_list'),
]

marcador_site/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marcador.urls')),
    path(
        'login/',
         auth_views.LoginView.as_view(template_name='login.html', ),
         name='site_login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(next_page=reverse_lazy('marcador:marcador_bookmark_list'), ),
        name='site_logout',
    ),
]

marcador/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'
        ordering = ['name']

    def __str__(self):
        return self.name


class PublicBookmarkManager(models.Manager):
    def get_queryset(self):
        qs = super(PublicBookmarkManager, self).get_queryset()
        return qs.filter(is_public=True)


class Bookmark(models.Model):
    url = models.URLField()
    title = models.CharField('title', max_length=255)
    description = models.TextField('description', blank=True)
    is_public = models.BooleanField('public', default=True)
    date_created = models.DateTimeField('date created', auto_now_add=True)
    date_updated = models.DateTimeField('date updated', auto_now=True)
    owner = models.ForeignKey(User, verbose_name='owner',
                              related_name='bookmarks',
                              on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tag, blank=True)

    objects = models.Manager()
    public = PublicBookmarkManager()

    class Meta:
        verbose_name = 'bookmark'
        verbose_name_plural = 'bookmarks'
        ordering = ['-date_created']

    def __str__(self):
        return '%s (%s)' % (self.title, self.url)

marcador/forms.py
from django.forms import ModelForm

from .models import Bookmark


class BookmarkForm(ModelForm):
    class Meta:
        model = Bookmark
        exclude = ('date_created', 'date_updated', 'owner')

marcador/views.py
from django.contrib.auth.decorators  import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render

from .forms import BookmarkForm
from .models import Bookmark


def bookmark_list(request):
    bookmarks = Bookmark.public.all()
    if request.GET.get('tag'):
        bookmarks = bookmarks.filter(tags__name=request.GET['tag'])
    context = {
        'bookmarks': bookmarks
    }
    return render(request, 'marcador/bookmark_list.html', context)


def bookmark_user(request, username):
    user = get_object_or_404(User, username=username)
    if request.user == user:
        bookmarks = user.bookmarks.all()
    else:
        bookmarks = Bookmark.public.filter(owner__username=username)
    if request.GET.get('tag'):
        bookmarks = bookmarks.filter(tags__name=request.GET['tag'])
    context = {
        'bookmarks': bookmarks,
        'owner': user,
    }
    return render(request, 'marcador/bookmark_user.html', context)


@login_required
def bookmark_create(request):
    if request.method == 'POST':
        form = BookmarkForm(data=request.POST)
        if form.is_valid():
            bookmark = form.save(commit=False)
            bookmark.owner = request.user
            bookmark.save()
            form.save_m2m()
            return redirect('marcador:marcador_bookmark_user',
                            username=request.user.username)
    else:
        form = BookmarkForm()
    context = {
        'form': form,
        'create': True,
    }
    return render(request, 'marcador/form.html', context)


@login_required
def bookmark_edit(request, pk):
    bookmark = get_object_or_404(Bookmark, pk=pk)
    if bookmark.owner != request.user and not request.user.is_superuser:
        raise PermissionDenied
    if request.method == 'POST':
        form = BookmarkForm(instance=bookmark, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('marcador:marcador_bookmark_user',
                            username=request.user.username)
    else:
        form = BookmarkForm(instance=bookmark)
    context = {
        'form': form,
        'create': False,
    }
    return render(request, 'marcador/form.html', context)

marcador/templates/marcador/bookmark.html
<a href="{{ bookmark.url }}" class="lead">{{ bookmark.title }}</a>
{% if bookmark.description|linebreaksbr %}
  <br>{{ bookmark.description|linebreaksbr }}
{% endif %}
{% if not bookmark.is_public %}
  <br><span class="label label-warning">private</span>
{% else %}
  <br>
{% endif %}
{% if bookmark.tags.count %}
  {% for tag in bookmark.tags.all %}
      <span class="label label-primary">{{ tag|lower }}</span>&nbsp;
  {% endfor %}
{% endif %}
<br>by <a href="{% url "marcador:marcador_bookmark_user" bookmark.owner.username %}">{{ bookmark.owner.username }}</a>
{{ bookmark.date_created|timesince }} ago
{% if bookmark.owner == user or user.is_superuser %}
  <br><a href="{% url "marcador:marcador_bookmark_edit" bookmark.pk %}"
        class="btn btn-default btn-xs" role="button">Edit bookmark</a>
{% endif %}

marcador/templates/marcador/bookmark_list.html
{% extends "base.html" %}

{% block title %}Latest bookmarks{% endblock %}

{% block heading %}
  <h2>Latest bookmarks</h2>
{% endblock %}

{% block content %}
  <ul class="list-unstyled">
  {% for bookmark in bookmarks %}
    <li class="well well-sm">{% include "marcador/bookmark.html" %}</li>
  {% empty %}
    <li>No bookmarks :(</li>
  {% endfor %}
  </ul>
{% endblock %}

marcador/templates/marcador/bookmark_user.html
{% extends "./bookmark_list.html" %}
{% load marcador_tags %}

{% block title %}{{ owner.username }}'s bookmarks{% endblock title %}

{% block heading %}
  <h2>
    {{ owner.username }}'s bookmarks
    <small>{{ bookmark.count }} bookmarks is total</small>
  </h2>
{% endblock %}

{% block sidebar %}
  {% tagcloud owner %}
{% endblock sidebar %}

marcador/templates/marcador/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  {% if create %}Create{% else %}Edit{% endif %} bookmark
{% endblock title %}

{% block heading %}
  <h2>{% if create %}Create{% else %}Edit{% endif %} bookmark</h2>
{% endblock heading %}

{% block content %}
  {% if create %}
    {% url 'marcador:marcador_bookmark_create' as action_url %}
  {% else %}
    {% url 'marcador:marcador_bookmark_edit' as action_url %}
  {% endif %}

  <form action="{{ action_url }}" method="post" accept-charset="utf-8">
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" class="btn btn-default" value="Save"></p>
  </form>
{% endblock content %}

templates/base.html
{% load staticfiles marcador_tags %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Marcador - {% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">

        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static  "css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% block toggle_login %}
            {% include "toggle_login.html" %}
          {% endblock toggle_login %}
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% block heading %} {% endblock %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          {% block content %} {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="panel panel-primary">
            <div class="panel-heading">Tag cloud</div>
            <div class="panel-body">
              {% block sidebar %}
                {% tagcloud %}
              {% endblock sidebar %}
            </div>
          </div>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>
    </div> <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block toggle_login %}{% endblock toggle_login %}

{% block heading %}
  <h2>Login</h2>
{% endblock heading %}

{% block content %}
  <form action="{% url "site_login" %}" method="post" accept-charset="utf-8">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" class="btn btn-default" value="Login">
  </form>
{% endblock content %}

templates/toggle_login.html
{% if user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
  <li><a href="{% url "marcador:marcador_bookmark_create" %}">Create bookmark</a></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
        aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url "marcador:marcador_bookmark_user" user.username %}"></a></li>
      <li><a href="{% url "site_logout" %}">Logout</a></li>
    </ul>
  </li>
</ul>
{% else %}
<form class="navbar-form navbar-right" role="form" action="{% url "site_login" %}?next={{ request.path }}"
    method="post" accept-charset="urf-8">
  <div class="form-group">
    <input type="text" placeholder="Username" class="form-control" name="username">
  </div>
  <div class="form-group">
    <input type="password" placeholder="Password" class="form-control" name="password">
  </div>
  {% csrf_token %}
  <button type="submit" class="btn btn-success">Sign in</button>
</form>
{% endif %}